### ISSUE TITLE
Error from stats.json

### ISSUE THREAD

**Issue by ahabhgk** [samccone/bundle-buddy#80]
`stats.json`:
```importing graph contents: 
TypeError: Cannot read properties of null (reading 'length')
----
Error: importing graph contents: 
TypeError: Cannot read properties of null (reading 'length')
    at https://bundle-buddy.com/static/js/6.91f14622.chunk.js:1:13457
    at l (https://bundle-buddy.com/static/js/3.2ccf6d4c.chunk.js:2:243533)
    at Generator._invoke (https://bundle-buddy.com/static/js/3.2ccf6d4c.chunk.js:2:243286)
    at forEach.e.<computed> [as next] (https://bundle-buddy.com/static/js/3.2ccf6d4c.chunk.js:2:243890)
    at r (https://bundle-buddy.com/static/js/3.2ccf6d4c.chunk.js:2:71944)
    at u (https://bundle-buddy.com/static/js/3.2ccf6d4c.chunk.js:2:72147)```

**Comment by ahabhgk** [comment]
<details>
  <summary>stats.json</summary>
  
```json
{
  "hash": "0f0d8995cba70eb476aa",
  "version": "5.74.0",
  "time": 303,
  "builtAt": 1665219365811,
  "publicPath": "auto",
  "outputPath": "/Users/bytedance/Codes/webpack5/dist",
  "assetsByChunkName": {
    "main": [
      "main.js"
    ]
  },
  "assets": [
    {
      "type": "asset",
      "name": "main.js",
      "size": 548850,
      "emitted": false,
      "comparedForEmit": true,
      "cached": false,
      "info": {
        "javascriptModule": false,
        "related": {
          "sourceMap": "main.js.map"
        },
        "size": 548850
      },
      "chunkNames": [
        "main"
      ],
      "chunkIdHints": [],
      "auxiliaryChunkNames": [],
      "auxiliaryChunkIdHints": [],
      "filteredRelated": 0,
      "related": [
        {
          "type": "sourceMap",
          "name": "main.js.map",
          "size": 673613,
          "emitted": false,
          "comparedForEmit": true,
          "cached": false,
          "info": {
            "development": true,
            "size": 673613
          },
          "chunkNames": [],
          "chunkIdHints": [],
          "auxiliaryChunkNames": [
            "main"
          ],
          "auxiliaryChunkIdHints": [],
          "related": {},
          "chunks": [],
          "auxiliaryChunks": [
            "main"
          ],
          "isOverSizeLimit": false
        }
      ],
      "chunks": [
        "main"
      ],
      "auxiliaryChunks": [],
      "isOverSizeLimit": false
    }
  ],
  "chunks": [
    {
      "rendered": true,
      "initial": true,
      "entry": true,
      "recorded": false,
      "size": 545675,
      "sizes": {
        "javascript": 544394,
        "runtime": 1281
      },
      "names": [
        "main"
      ],
      "idHints": [],
      "runtime": [
        "main"
      ],
      "files": [
        "main.js"
      ],
      "auxiliaryFiles": [
        "main.js.map"
      ],
      "hash": "580cc97badebe9e4c6f3",
      "childrenByOrder": {},
      "id": "main",
      "siblings": [],
      "parents": [],
      "children": [],
      "modules": [
        {
          "type": "module",
          "moduleType": "javascript/auto",
          "layer": null,
          "size": 544098,
          "sizes": {
            "javascript": 544098
          },
          "built": true,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "name": "./node_modules/lodash/lodash.js",
          "nameForCondition": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "index": 1,
          "preOrderIndex": 1,
          "index2": 0,
          "postOrderIndex": 0,
          "cacheable": true,
          "optional": false,
          "orphan": false,
          "dependent": true,
          "issuer": "/Users/bytedance/Codes/webpack5/src/index.js",
          "issuerName": "./src/index.js",
          "issuerPath": [
            {
              "identifier": "/Users/bytedance/Codes/webpack5/src/index.js",
              "name": "./src/index.js",
              "id": "./src/index.js"
            }
          ],
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "./node_modules/lodash/lodash.js",
          "issuerId": "./src/index.js",
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "module": "./node_modules/lodash/lodash.js",
              "moduleName": "./node_modules/lodash/lodash.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "resolvedModule": "./node_modules/lodash/lodash.js",
              "type": "cjs self exports reference",
              "active": true,
              "explanation": "",
              "userRequest": null,
              "loc": "439:50-57",
              "moduleId": "./node_modules/lodash/lodash.js",
              "resolvedModuleId": "./node_modules/lodash/lodash.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "module": "./node_modules/lodash/lodash.js",
              "moduleName": "./node_modules/lodash/lodash.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "resolvedModule": "./node_modules/lodash/lodash.js",
              "type": "cjs self exports reference",
              "active": true,
              "explanation": "",
              "userRequest": null,
              "loc": "439:62-78",
              "moduleId": "./node_modules/lodash/lodash.js",
              "resolvedModuleId": "./node_modules/lodash/lodash.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "module": "./node_modules/lodash/lodash.js",
              "moduleName": "./node_modules/lodash/lodash.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "resolvedModule": "./node_modules/lodash/lodash.js",
              "type": "cjs self exports reference",
              "active": true,
              "explanation": "",
              "userRequest": null,
              "loc": "439:82-89",
              "moduleId": "./node_modules/lodash/lodash.js",
              "resolvedModuleId": "./node_modules/lodash/lodash.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "module": "./node_modules/lodash/lodash.js",
              "moduleName": "./node_modules/lodash/lodash.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "resolvedModule": "./node_modules/lodash/lodash.js",
              "type": "module decorator",
              "active": true,
              "explanation": "",
              "userRequest": null,
              "loc": "442:63-69",
              "moduleId": "./node_modules/lodash/lodash.js",
              "resolvedModuleId": "./node_modules/lodash/lodash.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "module": "./node_modules/lodash/lodash.js",
              "moduleName": "./node_modules/lodash/lodash.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "resolvedModule": "./node_modules/lodash/lodash.js",
              "type": "module decorator",
              "active": true,
              "explanation": "",
              "userRequest": null,
              "loc": "442:74-80",
              "moduleId": "./node_modules/lodash/lodash.js",
              "resolvedModuleId": "./node_modules/lodash/lodash.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "module": "./node_modules/lodash/lodash.js",
              "moduleName": "./node_modules/lodash/lodash.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "resolvedModule": "./node_modules/lodash/lodash.js",
              "type": "module decorator",
              "active": true,
              "explanation": "",
              "userRequest": null,
              "loc": "442:93-99",
              "moduleId": "./node_modules/lodash/lodash.js",
              "resolvedModuleId": "./node_modules/lodash/lodash.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "module": "./node_modules/lodash/lodash.js",
              "moduleName": "./node_modules/lodash/lodash.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
              "resolvedModule": "./node_modules/lodash/lodash.js",
              "type": "cjs self exports reference",
              "active": true,
              "explanation": "",
              "userRequest": null,
              "loc": "17209:7-11",
              "moduleId": "./node_modules/lodash/lodash.js",
              "resolvedModuleId": "./node_modules/lodash/lodash.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
              "module": "./src/index.js",
              "moduleName": "./src/index.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
              "resolvedModule": "./src/index.js",
              "type": "harmony side effect evaluation",
              "active": true,
              "explanation": "",
              "userRequest": "lodash",
              "loc": "1:0-23",
              "moduleId": "./src/index.js",
              "resolvedModuleId": "./src/index.js"
            },
            {
              "moduleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
              "module": "./src/index.js",
              "moduleName": "./src/index.js",
              "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
              "resolvedModule": "./src/index.js",
              "type": "harmony import specifier",
              "active": true,
              "explanation": "",
              "userRequest": "lodash",
              "loc": "7:22-28",
              "moduleId": "./src/index.js",
              "resolvedModuleId": "./src/index.js"
            }
          ],
          "usedExports": null,
          "providedExports": null,
          "optimizationBailout": [
            "CommonJS bailout: this is used directly at 17209:7-11",
            "CommonJS bailout: exports is used directly at 439:50-57",
            "CommonJS bailout: exports is used directly at 439:82-89"
          ],
          "depth": 1
        },
        {
          "type": "module",
          "moduleType": "javascript/auto",
          "layer": null,
          "size": 296,
          "sizes": {
            "javascript": 296
          },
          "built": true,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "/Users/bytedance/Codes/webpack5/src/index.js",
          "name": "./src/index.js",
          "nameForCondition": "/Users/bytedance/Codes/webpack5/src/index.js",
          "index": 0,
          "preOrderIndex": 0,
          "index2": 1,
          "postOrderIndex": 1,
          "cacheable": true,
          "optional": false,
          "orphan": false,
          "dependent": false,
          "issuer": null,
          "issuerName": null,
          "issuerPath": null,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "./src/index.js",
          "issuerId": null,
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [
            {
              "moduleIdentifier": null,
              "module": null,
              "moduleName": null,
              "resolvedModuleIdentifier": null,
              "resolvedModule": null,
              "type": "entry",
              "active": true,
              "explanation": "",
              "userRequest": "./src/index.js",
              "loc": "main",
              "moduleId": null,
              "resolvedModuleId": null
            }
          ],
          "usedExports": null,
          "providedExports": [],
          "optimizationBailout": [],
          "depth": 0
        },
        {
          "type": "module",
          "moduleType": "runtime",
          "layer": null,
          "size": 267,
          "sizes": {
            "runtime": 267
          },
          "built": false,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "webpack/runtime/compat get default export",
          "name": "webpack/runtime/compat get default export",
          "nameForCondition": null,
          "index": null,
          "preOrderIndex": null,
          "index2": null,
          "postOrderIndex": null,
          "optional": false,
          "orphan": false,
          "dependent": false,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "",
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [],
          "usedExports": null,
          "providedExports": [],
          "optimizationBailout": [],
          "depth": null
        },
        {
          "type": "module",
          "moduleType": "runtime",
          "layer": null,
          "size": 308,
          "sizes": {
            "runtime": 308
          },
          "built": false,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "webpack/runtime/define property getters",
          "name": "webpack/runtime/define property getters",
          "nameForCondition": null,
          "index": null,
          "preOrderIndex": null,
          "index2": null,
          "postOrderIndex": null,
          "optional": false,
          "orphan": false,
          "dependent": false,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "",
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [],
          "usedExports": null,
          "providedExports": [],
          "optimizationBailout": [],
          "depth": null
        },
        {
          "type": "module",
          "moduleType": "runtime",
          "layer": null,
          "size": 221,
          "sizes": {
            "runtime": 221
          },
          "built": false,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "webpack/runtime/global",
          "name": "webpack/runtime/global",
          "nameForCondition": null,
          "index": null,
          "preOrderIndex": null,
          "index2": null,
          "postOrderIndex": null,
          "optional": false,
          "orphan": false,
          "dependent": false,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "",
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [],
          "usedExports": null,
          "providedExports": [],
          "optimizationBailout": [],
          "depth": null
        },
        {
          "type": "module",
          "moduleType": "runtime",
          "layer": null,
          "size": 88,
          "sizes": {
            "runtime": 88
          },
          "built": false,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "webpack/runtime/hasOwnProperty shorthand",
          "name": "webpack/runtime/hasOwnProperty shorthand",
          "nameForCondition": null,
          "index": null,
          "preOrderIndex": null,
          "index2": null,
          "postOrderIndex": null,
          "optional": false,
          "orphan": false,
          "dependent": false,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "",
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [],
          "usedExports": null,
          "providedExports": [],
          "optimizationBailout": [],
          "depth": null
        },
        {
          "type": "module",
          "moduleType": "runtime",
          "layer": null,
          "size": 274,
          "sizes": {
            "runtime": 274
          },
          "built": false,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "webpack/runtime/make namespace object",
          "name": "webpack/runtime/make namespace object",
          "nameForCondition": null,
          "index": null,
          "preOrderIndex": null,
          "index2": null,
          "postOrderIndex": null,
          "optional": false,
          "orphan": false,
          "dependent": false,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "",
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [],
          "usedExports": null,
          "providedExports": [],
          "optimizationBailout": [],
          "depth": null
        },
        {
          "type": "module",
          "moduleType": "runtime",
          "layer": null,
          "size": 123,
          "sizes": {
            "runtime": 123
          },
          "built": false,
          "codeGenerated": true,
          "buildTimeExecuted": false,
          "cached": false,
          "identifier": "webpack/runtime/node module decorator",
          "name": "webpack/runtime/node module decorator",
          "nameForCondition": null,
          "index": null,
          "preOrderIndex": null,
          "index2": null,
          "postOrderIndex": null,
          "optional": false,
          "orphan": false,
          "dependent": false,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "id": "",
          "chunks": [
            "main"
          ],
          "assets": [],
          "reasons": [],
          "usedExports": null,
          "providedExports": [],
          "optimizationBailout": [],
          "depth": null
        }
      ],
      "origins": [
        {
          "module": "",
          "moduleIdentifier": "",
          "moduleName": "",
          "loc": "main",
          "request": "./src/index.js"
        }
      ]
    }
  ],
  "modules": [
    {
      "type": "module",
      "moduleType": "javascript/auto",
      "layer": null,
      "size": 296,
      "sizes": {
        "javascript": 296
      },
      "built": true,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "/Users/bytedance/Codes/webpack5/src/index.js",
      "name": "./src/index.js",
      "nameForCondition": "/Users/bytedance/Codes/webpack5/src/index.js",
      "index": 0,
      "preOrderIndex": 0,
      "index2": 1,
      "postOrderIndex": 1,
      "cacheable": true,
      "optional": false,
      "orphan": false,
      "issuer": null,
      "issuerName": null,
      "issuerPath": null,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "./src/index.js",
      "issuerId": null,
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [
        {
          "moduleIdentifier": null,
          "module": null,
          "moduleName": null,
          "resolvedModuleIdentifier": null,
          "resolvedModule": null,
          "type": "entry",
          "active": true,
          "explanation": "",
          "userRequest": "./src/index.js",
          "loc": "main",
          "moduleId": null,
          "resolvedModuleId": null
        }
      ],
      "usedExports": null,
      "providedExports": [],
      "optimizationBailout": [],
      "depth": 0
    },
    {
      "type": "module",
      "moduleType": "javascript/auto",
      "layer": null,
      "size": 544098,
      "sizes": {
        "javascript": 544098
      },
      "built": true,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
      "name": "./node_modules/lodash/lodash.js",
      "nameForCondition": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
      "index": 1,
      "preOrderIndex": 1,
      "index2": 0,
      "postOrderIndex": 0,
      "cacheable": true,
      "optional": false,
      "orphan": false,
      "issuer": "/Users/bytedance/Codes/webpack5/src/index.js",
      "issuerName": "./src/index.js",
      "issuerPath": [
        {
          "identifier": "/Users/bytedance/Codes/webpack5/src/index.js",
          "name": "./src/index.js",
          "id": "./src/index.js"
        }
      ],
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "./node_modules/lodash/lodash.js",
      "issuerId": "./src/index.js",
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "module": "./node_modules/lodash/lodash.js",
          "moduleName": "./node_modules/lodash/lodash.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "resolvedModule": "./node_modules/lodash/lodash.js",
          "type": "cjs self exports reference",
          "active": true,
          "explanation": "",
          "userRequest": null,
          "loc": "439:50-57",
          "moduleId": "./node_modules/lodash/lodash.js",
          "resolvedModuleId": "./node_modules/lodash/lodash.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "module": "./node_modules/lodash/lodash.js",
          "moduleName": "./node_modules/lodash/lodash.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "resolvedModule": "./node_modules/lodash/lodash.js",
          "type": "cjs self exports reference",
          "active": true,
          "explanation": "",
          "userRequest": null,
          "loc": "439:62-78",
          "moduleId": "./node_modules/lodash/lodash.js",
          "resolvedModuleId": "./node_modules/lodash/lodash.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "module": "./node_modules/lodash/lodash.js",
          "moduleName": "./node_modules/lodash/lodash.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "resolvedModule": "./node_modules/lodash/lodash.js",
          "type": "cjs self exports reference",
          "active": true,
          "explanation": "",
          "userRequest": null,
          "loc": "439:82-89",
          "moduleId": "./node_modules/lodash/lodash.js",
          "resolvedModuleId": "./node_modules/lodash/lodash.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "module": "./node_modules/lodash/lodash.js",
          "moduleName": "./node_modules/lodash/lodash.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "resolvedModule": "./node_modules/lodash/lodash.js",
          "type": "module decorator",
          "active": true,
          "explanation": "",
          "userRequest": null,
          "loc": "442:63-69",
          "moduleId": "./node_modules/lodash/lodash.js",
          "resolvedModuleId": "./node_modules/lodash/lodash.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "module": "./node_modules/lodash/lodash.js",
          "moduleName": "./node_modules/lodash/lodash.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "resolvedModule": "./node_modules/lodash/lodash.js",
          "type": "module decorator",
          "active": true,
          "explanation": "",
          "userRequest": null,
          "loc": "442:74-80",
          "moduleId": "./node_modules/lodash/lodash.js",
          "resolvedModuleId": "./node_modules/lodash/lodash.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "module": "./node_modules/lodash/lodash.js",
          "moduleName": "./node_modules/lodash/lodash.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "resolvedModule": "./node_modules/lodash/lodash.js",
          "type": "module decorator",
          "active": true,
          "explanation": "",
          "userRequest": null,
          "loc": "442:93-99",
          "moduleId": "./node_modules/lodash/lodash.js",
          "resolvedModuleId": "./node_modules/lodash/lodash.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "module": "./node_modules/lodash/lodash.js",
          "moduleName": "./node_modules/lodash/lodash.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/node_modules/lodash/lodash.js",
          "resolvedModule": "./node_modules/lodash/lodash.js",
          "type": "cjs self exports reference",
          "active": true,
          "explanation": "",
          "userRequest": null,
          "loc": "17209:7-11",
          "moduleId": "./node_modules/lodash/lodash.js",
          "resolvedModuleId": "./node_modules/lodash/lodash.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
          "module": "./src/index.js",
          "moduleName": "./src/index.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
          "resolvedModule": "./src/index.js",
          "type": "harmony side effect evaluation",
          "active": true,
          "explanation": "",
          "userRequest": "lodash",
          "loc": "1:0-23",
          "moduleId": "./src/index.js",
          "resolvedModuleId": "./src/index.js"
        },
        {
          "moduleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
          "module": "./src/index.js",
          "moduleName": "./src/index.js",
          "resolvedModuleIdentifier": "/Users/bytedance/Codes/webpack5/src/index.js",
          "resolvedModule": "./src/index.js",
          "type": "harmony import specifier",
          "active": true,
          "explanation": "",
          "userRequest": "lodash",
          "loc": "7:22-28",
          "moduleId": "./src/index.js",
          "resolvedModuleId": "./src/index.js"
        }
      ],
      "usedExports": null,
      "providedExports": null,
      "optimizationBailout": [
        "CommonJS bailout: this is used directly at 17209:7-11",
        "CommonJS bailout: exports is used directly at 439:50-57",
        "CommonJS bailout: exports is used directly at 439:82-89"
      ],
      "depth": 1
    },
    {
      "type": "module",
      "moduleType": "runtime",
      "layer": null,
      "size": 267,
      "sizes": {
        "runtime": 267
      },
      "built": false,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "webpack/runtime/compat get default export",
      "name": "webpack/runtime/compat get default export",
      "nameForCondition": null,
      "index": null,
      "preOrderIndex": null,
      "index2": null,
      "postOrderIndex": null,
      "optional": false,
      "orphan": false,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "",
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [],
      "usedExports": null,
      "providedExports": [],
      "optimizationBailout": [],
      "depth": null
    },
    {
      "type": "module",
      "moduleType": "runtime",
      "layer": null,
      "size": 308,
      "sizes": {
        "runtime": 308
      },
      "built": false,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "webpack/runtime/define property getters",
      "name": "webpack/runtime/define property getters",
      "nameForCondition": null,
      "index": null,
      "preOrderIndex": null,
      "index2": null,
      "postOrderIndex": null,
      "optional": false,
      "orphan": false,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "",
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [],
      "usedExports": null,
      "providedExports": [],
      "optimizationBailout": [],
      "depth": null
    },
    {
      "type": "module",
      "moduleType": "runtime",
      "layer": null,
      "size": 221,
      "sizes": {
        "runtime": 221
      },
      "built": false,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "webpack/runtime/global",
      "name": "webpack/runtime/global",
      "nameForCondition": null,
      "index": null,
      "preOrderIndex": null,
      "index2": null,
      "postOrderIndex": null,
      "optional": false,
      "orphan": false,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "",
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [],
      "usedExports": null,
      "providedExports": [],
      "optimizationBailout": [],
      "depth": null
    },
    {
      "type": "module",
      "moduleType": "runtime",
      "layer": null,
      "size": 88,
      "sizes": {
        "runtime": 88
      },
      "built": false,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "webpack/runtime/hasOwnProperty shorthand",
      "name": "webpack/runtime/hasOwnProperty shorthand",
      "nameForCondition": null,
      "index": null,
      "preOrderIndex": null,
      "index2": null,
      "postOrderIndex": null,
      "optional": false,
      "orphan": false,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "",
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [],
      "usedExports": null,
      "providedExports": [],
      "optimizationBailout": [],
      "depth": null
    },
    {
      "type": "module",
      "moduleType": "runtime",
      "layer": null,
      "size": 274,
      "sizes": {
        "runtime": 274
      },
      "built": false,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "webpack/runtime/make namespace object",
      "name": "webpack/runtime/make namespace object",
      "nameForCondition": null,
      "index": null,
      "preOrderIndex": null,
      "index2": null,
      "postOrderIndex": null,
      "optional": false,
      "orphan": false,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "",
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [],
      "usedExports": null,
      "providedExports": [],
      "optimizationBailout": [],
      "depth": null
    },
    {
      "type": "module",
      "moduleType": "runtime",
      "layer": null,
      "size": 123,
      "sizes": {
        "runtime": 123
      },
      "built": false,
      "codeGenerated": true,
      "buildTimeExecuted": false,
      "cached": false,
      "identifier": "webpack/runtime/node module decorator",
      "name": "webpack/runtime/node module decorator",
      "nameForCondition": null,
      "index": null,
      "preOrderIndex": null,
      "index2": null,
      "postOrderIndex": null,
      "optional": false,
      "orphan": false,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "id": "",
      "chunks": [
        "main"
      ],
      "assets": [],
      "reasons": [],
      "usedExports": null,
      "providedExports": [],
      "optimizationBailout": [],
      "depth": null
    }
  ],
  "entrypoints": {
    "main": {
      "name": "main",
      "chunks": [
        "main"
      ],
      "assets": [
        {
          "name": "main.js",
          "size": 548850
        }
      ],
      "filteredAssets": 0,
      "assetsSize": 548850,
      "auxiliaryAssets": [
        {
          "name": "main.js.map",
          "size": 673613
        }
      ],
      "filteredAuxiliaryAssets": 0,
      "auxiliaryAssetsSize": 673613,
      "children": {},
      "childAssets": {},
      "isOverSizeLimit": false
    }
  },
  "namedChunkGroups": {
    "main": {
      "name": "main",
      "chunks": [
        "main"
      ],
      "assets": [
        {
          "name": "main.js",
          "size": 548850
        }
      ],
      "filteredAssets": 0,
      "assetsSize": 548850,
      "auxiliaryAssets": [
        {
          "name": "main.js.map",
          "size": 673613
        }
      ],
      "filteredAuxiliaryAssets": 0,
      "auxiliaryAssetsSize": 673613,
      "children": {},
      "childAssets": {},
      "isOverSizeLimit": false
    }
  },
  "errors": [],
  "errorsCount": 0,
  "warnings": [],
  "warningsCount": 0,
  "children": []
}
```
</details>

**Comment by JSerFeng** [comment]
same issue, any update ?
